Italian translation
ZeroK-RTS/Chobby pull request #857
Opened 2023-06-02 05:58 UTC by fvasco

2023-06-23 23:18 UTC, sprunk commented on LuaMenu/widgets/chobby/i18n/chililobby.lua
> +		},
did something break here? there is an unmatched `}` bracket.

2023-06-23 23:18 UTC, sprunk commented on LuaMenu/widgets/chobby/i18n/chililobby.lua
> +		advanced_button_tooltip = [[Fully configure game settings. Activate automatic advanced mode by disabling "Simple skirmish setup" in lobby settings.]],
looks untranslated

2023-06-23 23:19 UTC, sprunk commented on LuaMenu/widgets/chobby/i18n/chililobby.lua
> +		match_found_quickplay = "Small Teams available",
looks untranslated

2023-06-23 23:22 UTC, sprunk requested changes
Sorry for the late review! Looks decent overall, but there are some things to fix (left specific comments under the relevant lines). Also there needs to be an entry in the list of languages for it to show up on the list, here: https://github.com/ZeroK-RTS/Chobby/blob/d2ab5342a14535e47f854e72218033bf3ada2d7b/LuaMenu/widgets/chobby/components/configuration.lua#L254-L257

2023-06-24 20:04 UTC, fvasco commented
Thank you for review.
I updated files.

2023-07-11 22:14 UTC, merged

2023-07-11 22:15 UTC, sprunk commented
Thanks!